"""User-facing explanations and choices shared by the configuration forms."""

HELP = {
    "classifier_models": "Use the same logistic or MLP estimators as Tools, or K-nearest neighbors. Scores and confusion matrices come from held-out folds.",
    "classify": "Evaluate predictive performance when enough labels exist. Turn off to overlay known labels without fitting a classifier.",
    "minimum_class_count": "Exclude classes with fewer matched labeled objects from classifier training and evaluation; their known labels remain on the plots.",
    "fold_policy": "reduce uses as many stratified folds as the smallest eligible class permits, matching Tools. strict rejects insufficient class counts. Specimen groups must also support the requested folds.",
    "class_weight": "balanced weights each class inversely to its training-fold count, matching the classification Tool default. null gives equal weight to individual objects. Applies to logistic regression.",
    "hidden_dimensions": "MLP hidden-layer widths, such as [64] for the same one-hidden-layer network used in Tools. ReLU activation and L2 penalty 0.0001 are shared.",
    "predict_unlabeled": "Fit on eligible labeled objects to predict types for other objects. Evaluated objects retain held-out predictions; fitted predictions are not validation evidence.",
    "prediction_model": "Classifier whose predicted labels are shown beside known types and used for categorical volume exports.",
    "unlabeled_opacity": "Opacity from 0 (invisible) to 1 (opaque) for objects without a known cell type. Applies to the same objects in adjacent cluster/class panels.",
    "input_config": "Optional mae_config.yaml or grouped N5 data YAML for point inspection. Extraction provenance supplies this automatically when available.",
    "subset": "Zero projects all embeddings. A positive count selects an ID-sorted, reproducible subset before normalization, matching Tools. Classification still uses all eligible labeled embeddings.",
    "umap_epochs": "Optimization epochs for UMAP. 50 matches Tools; null lets UMAP choose automatically. Match this, subset, minimum distance and seed when comparing plots.",
    "resolution": "Leiden CPM resolution on the weighted UMAP graph in normalized feature space. Higher values generally produce more clusters.",
    "labels": "Saved object_labels.tsv with exact label_id values and known_label, predicted_label and/or cluster columns.",
    "layers": "Categorical volumes to write on the original segmentation grid. Each layer has its own numeric category-to-color lookup table; zero is background or unassigned.",
    "id_mapping": "Optional CSV/TSV with label_id and segmentation_id (or the chosen mapping column). Required when embedding IDs refer to different objects than the segmentation. Many-to-one mappings are rejected as ambiguous.",
    "mapping_column": "Column in the mapping table containing exact integer IDs from the source segmentation.",
    "name": "A descriptive name for this editable workflow. The Run ID separately names the output directory.",
    "run_id": "Unique name for this execution and its output directory. Use letters, digits, dots, underscores, or dashes; completed or dry-run directories cannot be reused.",
    "execution": "local starts a worker on the app host; slurm submits the reviewed job to the cluster.",
    "allow_synthetic": "Permit generated demonstration crops when no real data is configured. Leave disabled for biological workflows so missing data produces an error.",
    "model": "Choose a trained MAE or a frozen pretrained DINOv2/DINOv3 backbone. Each requires matching weights and the corresponding input configuration.",
    "repo_root": "Location of the MorphoFeatures checkout. Repository-relative data paths are resolved from this directory; it does not select a dataset or submit a job.",
    "data_root": "Base directory for dataset files referenced by the configuration.",
    "output_root": "Directory for generated files. Workflow runs use the workspace output root shown on Review & run.",
    "analysis_data": "Directory containing the bundled reference embeddings and annotation tables.",
    "mobie_data": "Directory containing the published MoBIE tables used as reference data.",
    "run_dir": "Base output directory in the model configuration. Workflow submission places training outputs in this run's own stage directory.",
    "checkpoint": "Saved model weights. Extraction reads this file; training output checkpoints are placed in the current run directory.",
    "best_checkpoint": "Destination for the model with the best validation loss. Workflow submission scopes this to the current run.",
    "resolved_config": "Saved copy of the exact model and data settings used for training, retained with the checkpoint.",
    "metrics": "Training metric log, including losses and progress. Workflow submission writes it in this run's stage directory.",
    "metrics_path": "Training metric log used by the worker and Runs page; scoped to the current run on submission.",
    "split_manifest": "Table recording which object IDs belong to training, validation, and test sets.",
    "run_metadata": "Record of dataset, model, and execution provenance saved with training outputs.",
    "embedding": "Saved feature vectors with their object IDs. These are the input to projection and classification.",
    "crops": "Object intensity crops in NumPy, HDF5 or N5, shaped (objects, Z, Y, X) or (objects, channels, Z, Y, X). Containers also need a dataset key. Load the generated mae_config.yaml to fill in paths and keys.",
    "label_ids": "One integer object ID per crop. These IDs connect embeddings to segmentation objects and annotation tables.",
    "loss_masks": "Optional foreground masks aligned with the crops, in NumPy, HDF5 or N5. Training measures reconstruction inside the mask; DINO uses it to select object pixels. Containers also need a mask dataset key.",
    "crops_key": "Dataset holding intensity crops inside the HDF5/N5 container; preprocessing writes crops. This whole-object layout is separate from grouped N5 patches and their positions index.",
    "label_ids_key": "Dataset containing one exact integer ID per crop; preprocessing writes label_ids. Use the same row order as the crops and masks.",
    "loss_masks_key": "Dataset holding aligned foreground masks inside the HDF5/N5 container; preprocessing writes masks, with zero outside and one inside each object.",
    "output_format": "npy writes three NumPy arrays. h5 writes one HDF5 file; n5 writes an N5 directory. Both containers use compressed datasets for crops, masks and object IDs. All formats generate mae_config.yaml for subsequent MAE, DINO and preview use. HDF5 requires h5py; N5 requires z5py.",
    "raw": "Raw intensity volume, not a label image. Supported containers are HDF5, N5, Zarr, and .npy. It must share a spatial grid with the segmentation.",
    "segmentation": "Integer instance-label volume aligned with the raw image. Each object has a distinct positive ID; zero is background.",
    "raw_key": "Dataset inside the raw container, for example exported_data or volumes/raw/s1. Leave blank for a .npy file.",
    "segmentation_key": "Dataset inside the segmentation container. Select instance IDs at the same resolution as the raw image. Leave blank for .npy.",
    "raw_axes": "Order of dimensions as stored, for example zyx or zyxc. The preview and ROI controls convert spatial dimensions into Z, Y, X order.",
    "segmentation_axes": "Order of stored segmentation dimensions, for example zyx or zyxc. It can differ from raw storage order if both describe the same spatial grid.",
    "raw_channel": "Zero-based intensity channel to read when the raw volume has a channel dimension.",
    "segmentation_channel": "Zero-based channel containing instance IDs when the segmentation has a channel dimension.",
    "roi": "Region to process in Z, Y, X voxel coordinates: start is included and stop is excluded. Smaller regions reduce scanning time; null selects the full volume.",
    "crop_shape": "Fixed output size in Z, Y, X voxels for each object. Choose a size that contains the objects and is divisible by the MAE patch size.",
    "spacing_zyx": "Physical distance between voxels along Z, Y, X, expressed in the selected coordinate unit. Use 1, 1, 1 with voxel units when physical spacing is unknown.",
    "origin_zyx": "Coordinate of voxel zero in Z, Y, X order, in the selected coordinate unit. Raw and segmentation must use the same origin.",
    "unit": "Unit used for voxel spacing and exported object coordinates. ROI bounds always use voxel indices.",
    "max_objects": "Maximum number of eligible objects to export. Zero includes all eligible objects. The selected ROI is still scanned to establish object bounds.",
    "block_shape": "Size of each segmentation scan tile in Z, Y, X. Smaller tiles reduce working memory but may increase I/O overhead.",
    "min_voxels": "Discard objects with fewer than this many labeled voxels inside the selected ROI.",
    "object_ids": "Optional list of specific instance IDs to export. Leave empty to consider every object in the ROI.",
    "center": "Center crops on the bounding-box midpoint (bbox) or the object's voxel centroid (centroid).",
    "oversized": "skip excludes objects that do not fit the crop; clip keeps a truncated crop. Truncation is recorded in the object manifest.",
    "boundary": "pad fills parts of a crop extending outside the ROI with background; skip excludes such crops.",
    "roi_boundary": "skip excludes objects touching the ROI edge because their full extent is unknown; allow keeps them and records truncation.",
    "background": "Intensity assigned outside each object's mask after normalization, usually zero.",
    "seed": "Seed for repeatable splits, initialization, and randomized analysis. Identical seeds do not guarantee identical results across hardware or library versions.",
    "device": "auto uses CUDA when available, otherwise CPU. cuda requires a visible GPU; request GPUs separately when submitting to Slurm.",
    "input_shape": "Spatial input dimensions in Z, Y, X. Must match prepared crops or stored N5 patches. Linked preprocessing supplies this automatically.",
    "input_channels": "Number of image channels per input crop. The grouped nucleus workflow uses one grayscale channel.",
    "patch_size": "Z, Y, X size of each token within a crop. Each input dimension must be divisible by its patch dimension. Smaller patches create more tokens and use more memory.",
    "embedding_dim": "Number of encoder features per token and output object embedding. Must be divisible by the encoder's attention-head count.",
    "encoder_depth": "Number of transformer encoder layers. More layers increase model capacity, runtime, and memory use.",
    "encoder_heads": "Number of parallel encoder attention heads. Must divide the embedding dimension exactly.",
    "decoder_dim": "Width of the reconstruction decoder. For grouped MAE it must be divisible by decoder heads; the crop MAE uses an MLP decoder without attention heads.",
    "decoder_depth": "Number of transformer reconstruction-decoder layers in grouped MAE. This affects training cost; embeddings come from the encoder.",
    "decoder_heads": "Number of attention heads in the grouped MAE decoder. Must divide the decoder dimension exactly.",
    "mask_ratio": "Fraction of tokens hidden during reconstruction training, between 0 and 1. Grouped MAE hides complete stored patches; crop MAE hides internal voxel patches.",
    "reconstruction_shape": "Z, Y, X reconstruction target per stored patch in grouped MAE. Smaller targets lower decoder cost and discard fine detail.",
    "norm_pix_loss": "Normalize each grouped patch's reconstruction target before computing loss, reducing sensitivity to intensity scale.",
    "patch_encoder": "linear projects each stored patch directly into a token; resnet3d first learns local 3D convolutional features. Changing this requires a matching new checkpoint.",
    "resnet_channels": "Channel widths for successive 3D ResNet stages. Used only with the resnet3d patch encoder.",
    "resnet_blocks": "Residual-block counts for each 3D ResNet stage. Provide one count for each channel width.",
    "epochs": "Maximum number of passes through the training set. Grouped early stopping may finish before this limit.",
    "batch_size": "Number of samples processed together. Larger batches need more memory; a grouped sample contains multiple stored patches from one object.",
    "learning_rate": "AdamW optimizer step size. Reduce it if training is unstable; compare validation loss when tuning it.",
    "weight_decay": "AdamW regularization strength. Zero disables weight decay; larger values penalize large weights more strongly.",
    "workers": "Number of background data-loading processes. Zero reads in the training process; more workers can improve throughput on fast storage.",
    "pin_memory": "Use page-locked host memory for data batches, which can accelerate transfers to CUDA devices.",
    "scheduler": "Learning-rate schedule: constant keeps the rate fixed, cosine gradually decays it, and step reduces it at fixed epoch intervals.",
    "warmup_epochs": "Initial epochs used to ramp up the learning rate. Must be shorter than the full training run.",
    "min_learning_rate": "Lowest learning rate reached by cosine decay.",
    "scheduler_step_size": "Number of epochs between learning-rate reductions when using the step schedule.",
    "scheduler_gamma": "Multiplier applied at each step-schedule reduction, for example 0.5 halves the rate.",
    "mixed_precision": "Use mixed-precision computation on CUDA to reduce memory use and often speed training. CPU training remains full precision.",
    "checkpoint_interval": "Save an intermediate checkpoint every this many epochs. Zero disables periodic checkpoints; final/best checkpoint handling remains separate.",
    "progress_interval_batches": "Write progress and throughput every this many batches. Zero keeps epoch-level metrics only.",
    "resume_from": "Grouped MAE checkpoint to resume, including optimizer and scheduler state. Leave blank to start a new model.",
    "enabled": "Stop grouped training when validation loss no longer improves, using patience and minimum improvement below.",
    "patience": "Number of validation epochs without sufficient improvement before early stopping.",
    "min_delta": "Minimum reduction in validation loss counted as an improvement for early stopping.",
    "restore_best": "Restore the model and optimizer state from the best validation epoch for the final checkpoint.",
    "train_fraction": "Fraction of object IDs assigned to training. Grouped train, validation, and test fractions must sum to one.",
    "validation_fraction": "Fraction of object IDs held out from optimization to measure validation loss.",
    "test_fraction": "Fraction of object IDs reserved for final evaluation. Keep these objects out of training and model selection.",
    "max_labels": "Limit the grouped workflow to this many object IDs for a bounded trial. null uses all eligible IDs.",
    "group_size": "Number of complete stored patches sampled together from one nucleus. More patches capture more context and increase attention memory.",
    "patches_container": "N5 container holding stored intensity patches. Pair it with the positions index from the same dataset release.",
    "source": "Input layout used by the reader. n5_masked_patches selects indexed stored patches grouped by their biological parent ID.",
    "qc_raw_container": "Optional unmasked raw N5 volume for checking stored masked patches against their source imagery.",
    "qc_raw_key": "Dataset key for the raw pyramid level used in patch quality-control views.",
    "position_radius_zyx": "Half-size of a patch in the position-index grid, in Z, Y, X. Used to recover the corresponding raw crop for quality control.",
    "position_to_raw_scale_zyx": "Scale from the patch-center coordinate grid to the selected raw pyramid, in Z, Y, X. Use audited values for your dataset.",
    "modality": "Imaging modality recorded with this dataset, such as EM. This describes provenance; it does not convert the images.",
    "biological_unit": "Biological object represented by each output ID, such as nucleus or cell. Keep this consistent with annotations and comparisons.",
    "positions_container": "N5 container mapping patch rows to parent object IDs and spatial positions.",
    "patches_key": "Dataset key containing the stored patches inside the N5 container.",
    "positions_key": "Dataset key containing patch-to-object IDs and spatial coordinates.",
    "ids_key": "Dataset key containing the unique biological parent IDs in the positions container.",
    "position_stride_zyx": "Spacing between candidate patch centers in index coordinates, Z, Y, X. Must agree with the audited patch sampling grid.",
    "resolution_zyx_um": "Physical voxel spacing of stored image patches in micrometers, Z, Y, X.",
    "position_resolution_zyx_um": "Physical spacing of the coordinate grid used by patch-center positions, in micrometers, Z, Y, X.",
    "patch_shape_zyx": "Stored patch dimensions in Z, Y, X; these must match the N5 array and model input shape.",
    "min_foreground_fraction": "Exclude patches whose foreground mask covers less than this fraction of voxels.",
    "mask_mode": "nonzero treats nonzero intensities as foreground; all treats the entire stored patch as foreground.",
    "random_flip": "Grouped augmentation is currently disabled because image patches and spatial coordinates must transform together. Keep false.",
    "random_rot90": "Grouped augmentation is currently disabled pending matching spatial-coordinate transforms. Keep false.",
    "annotations": "CSV or TSV with unique label_id values and known classes. Only labeled objects enter classification; every object remains in the projection.",
    "cell_table": "Optional cell annotation table used to connect learned features to biological labels and metadata.",
    "cell_to_nucleus": "Optional mapping between cell IDs and nucleus IDs. Use an authoritative mapping from the same segmentation release.",
    "symmetric_cells": "Optional table of corresponding bilateral cells, used for biological interpretation checks.",
    "label_column": "Column containing known biological classes. auto detects cell_type, label or cell_label. Use external annotations rather than computed clusters as classification targets.",
    "group_column": "Optional specimen/acquisition column. All objects from one group stay in the same evaluation fold to reduce related-object leakage.",
    "folds": "Requested held-out folds. The reduce policy lowers this to the smallest eligible class count, matching Tools; strict requires every class to support this count. Grouped evaluation also needs enough independent groups.",
    "knn_k": "Number of training-set neighbors used for k-nearest-neighbor classification and retrieval checks.",
    "linear_c": "Inverse regularization strength of the linear classifier. Smaller values regularize more strongly.",
    "max_iter": "Maximum optimizer iterations for the linear classifier; increase if it fails to converge.",
    "evaluation_pca": "Optional feature dimensions retained before classification. PCA is fitted separately within each training fold; null disables it.",
    "umap": "Also compute a nonlinear UMAP projection. PCA is always saved. UMAP requires the optional analysis dependency and at least four objects.",
    "neighbors": "Neighborhood size used by UMAP and graph clustering. Smaller values emphasize local structure.",
    "min_dist": "UMAP point-packing parameter. Lower values form tighter visual groups; visual separation alone does not demonstrate biological classes.",
    "clusters": "Number of K-means clusters. This is an exploratory partition, not a count of validated biological cell types.",
    "cluster_method": "K-means uses a chosen cluster count; Leiden uses a neighborhood graph and a resolution parameter.",
    "model_repository": "Local checkout of the official DINOv2 or DINOv3 repository containing hubconf.py. Code and pretrained weights are supplied separately.",
    "variant": "Backbone architecture matching the supplied weights. DINOv2 and DINOv3 weights are not interchangeable.",
    "axes": "Axes used for 2D views: 0 is Z, 1 is Y, and 2 is X. Each selected axis contributes slices through each 3D object crop.",
    "fractions": "Slice positions along each selected axis, from 0 to 1. [0.5] uses central slices; [0.25, 0.5, 0.75] uses three slices per axis.",
    "size": "Square image size passed to DINO. Must be divisible by 14 for DINOv2 or 16 for DINOv3; 224 works for both.",
    "mask": "Set pixels outside the object mask to zero before producing DINO views, reducing contributions from adjacent objects.",
    "percentiles": "Lower and upper foreground intensity percentiles mapped to 0 and 1 before DINO encoding.",
    "resize": "letterbox preserves slice aspect ratio with padding; stretch resizes each slice to a square.",
    "feature": "cls uses the global class token; patch_mean averages the image's patch tokens. Both produce one vector per view.",
    "aggregation": "Combine all view vectors for each object by their mean or elementwise maximum.",
    "cache": "Directory for reusable embedding results. Checkpoint, data, and view settings determine the cache identity.",
    "data_version": "Change this identifier after modifying source volumes in place so extraction does not reuse an older cached result.",
    "sequential_ids": "Generate row-number IDs if an ID file is absent. Prefer original segmentation IDs when joining annotations or inspecting objects.",
    "partition": "Cluster queue to request. Choose a partition that provides the CPU/GPU resources required by your workflow.",
    "time": "Maximum wall-clock time, in HH:MM:SS or D-HH:MM:SS. Slurm can stop the job when this limit is reached.",
    "memory": "Memory reservation, for example 16G or 128G. All stages share this reservation.",
    "cpus": "CPU threads available to the worker; on Slurm this requests CPUs per task.",
    "gpus": "Number of GPUs to reserve. Set at least one for CUDA training or DINO extraction on Slurm.",
    "account": "Cluster allocation or billing account. Leave blank if the cluster assigns your default account.",
    "qos": "Optional cluster quality-of-service policy controlling limits and priority.",
    "nodes": "Number of nodes requested. This workspace runs a single worker and does not distribute training across nodes.",
    "ntasks": "Number of Slurm tasks reserved. The workspace launches one worker; extra tasks do not enable distributed training.",
    "ntasks_per_node": "Tasks reserved per node. Use one for the current single-worker pipeline.",
    "gpu_directive": "Use gres for clusters expecting --gres=gpu:N; use gpus for --gpus=N.",
    "mail_types": "Events for which Slurm should email you. Select END and FAIL for completion/failure notices and supply a mail address.",
    "mail_user": "Email recipient for selected Slurm events. Both an address and at least one notification event are required.",
    "python_executable": "Python interpreter from the environment containing MorphoFeatures and its dependencies. It must be accessible on the execution host.",
    "setup": "Environment setup before the worker starts. Enter argument lists, for example [[module, load, CUDA], [source, /path/to/activate.sh]].",
    "cpu_thread_env": "Set OMP and MKL thread counts to CPUs per task in the Slurm script to avoid oversubscribing CPU cores.",
    "local_runtime_directories": "Store selected optional W&B and Matplotlib caches inside the run directory.",
    "log_job_context": "Write job ID, host, working directory, and command into the job log for troubleshooting.",
}


def setting_help(path):
    parts = [str(part) for part in path if not isinstance(part, int)]
    key = parts[-1]
    if key.endswith("_spacing_zyx"):
        return "Voxel spacing for this volume, in Z, Y, X and the chosen unit. It must match the common grid; align or resample mismatched volumes first."
    if key.endswith("_origin_zyx"):
        return "Coordinate of this volume's voxel zero, in Z, Y, X. It must match the common origin for aligned preprocessing."
    if key == "normalization":
        if "views" in parts:
            return "DINO intensity scaling: foreground_percentile uses object intensities; dtype requires integer crops; unit expects values already in [0, 1]."
        if "data" in parts:
            return "Intensity scaling before encoding or crop export. dtype uses the integer data range; foreground_percentile uses object intensities; none preserves values."
        return "Scale embedding features before analysis: standardize centers each feature, l2 normalizes each object vector, and none preserves values. Classification fits learned scaling on training folds only."
    if key == "axes" and "views" not in parts:
        return "Spatial dimension order of stored patches; the grouped N5 workflow expects zyx."
    if key == "split" and "inference" in parts:
        return "Which object IDs to encode: training, validation, test, or all. Use test for held-out model checks."
    return HELP.get(
        key,
        "Additional option preserved from the loaded configuration. Its meaning is defined by the selected data or model adapter; keep the supplied value unless you intend to override it.",
    )
